# Generated by Django 5.0.7 on 2024-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeitem_price_storeitem_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
