# Generated by Django 5.0.7 on 2024-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storeitem_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
