# Generated by Django 5.0.7 on 2024-07-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storeitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='order',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='default_order',
            field=models.IntegerField(default=0),
        ),
    ]
